env:
  global:
    - secure: "IyoXDHoN0r5B8q00h/QVmRrfm1Xx3ig0zSd9n3V5tCm8njzMU7YFliV1iKXFyh03Lf+fIMntoJxTGY0z3ym0eki+kvfwENXBuzIfWXC8XOysQ1Fj7hhu3WCR94zh0ciAl3jw97k7wzoLz5okJnyTgoaxbwZn/TQ0pDSC/o9Z5Zo="
language: php
php:
  - 5.3
  - 5.4
  - 5.5
before_script:
  # Composer
  - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install
  - composer self-update
  - composer update --prefer-source
script:
  # PHPUnit tests
  - php vendor/bin/phpunit --configuration tests/phpunit.xml.dist --coverage-text
  - mkdir .reports
  # Code style
  - php vendor/bin/phpcs ./src/Yandex --standard=PSR1 --report=summary
  - php vendor/bin/phpcs ./src/Yandex --standard=PSR2 --report=summary
  # Duplicate code
  - php vendor/bin/phpcpd --log-pmd .reports/pmd-cpd.xml src/Yandex
after_success:
  #Share build:
  - composer update --no-dev
  - php phar.php
notifications:
  email: github@nixsolutions.com
